on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "18 7 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variant:
          - centos
          - alpine
          - ubuntu
          - lua51
    steps:
      - uses: actions/checkout@v1
      - name: Build Container
        run: docker-compose up -d ${{ matrix.variant }}
      - name: Lint
        run: docker-compose exec ${{ matrix.variant }} make lint
      - name: Test
        run: docker-compose exec ${{ matrix.variant }} make test
      - name: Copy Artifacts
        if: always()
        run: |
          rm -rf /tmp/resty-auto-ssl-test
          docker cp $(docker-compose ps -q ${{ matrix.variant }}):/tmp/resty-auto-ssl-test /tmp/resty-auto-ssl-test
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: logs
          path: /tmp/resty-auto-ssl-test
