on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variant:
          - centos
          - alpine
          - ubuntu
          - lua51
    steps:
      - uses: actions/checkout@v1
      - name: test1
        run: docker-compose run --rm ${{ matrix.variant }} env
      - name: test2
        run: docker-compose run --rm ${{ matrix.variant }} find .
      - name: test3
        run: docker-compose run --rm ${{ matrix.variant }} pwd
      - name: Lint
        run: docker-compose run --rm ${{ matrix.variant }} make lint
      - name: Test
        run: docker-compose run --rm ${{ matrix.variant }} make test
